
cc_test(
    name = "tokenizer",
    srcs = ["tokenizer.cc"],
    deps = [
      "//lib:linlib",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "tests",
    srcs = ["tests.cc"],
    deps = [
      "//lib:linlib",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "errors",
    srcs = ["errors.cc"],
    deps = [
      "//lib:linlib",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "calculator",
    srcs = ["calculator.cc"],
    deps = [
      "//lib:linlib",
      "@gtest//:gtest_main",
    ],
)

