
cc_library(
    name = "linlib",
    srcs = [
      "linlib.cc",
      "tokenizer.cc",
      "parser.cc",
    ],
    hdrs = [
      "linlib.h",
      "tokenizer.h",
      "parser.h",
    ],
    visibility = [
      "//visibility:public",
    ],
)
