
cc_library(
    name = "linlib",
    srcs = [
      "linlib.cc",
      "parser.cc",
    ],
    hdrs = [
      "linlib.h",
      "parser.h",
    ],
    visibility = [
      "//main:__pkg__",
      "//tests:__pkg__",
    ],
)
